# vim: set ft=yaml sw=2:
stages:
  - build
  - run
  - test
  - push
  - npins

default:
  tags:
    - nix
    - helsinki-hydra-builder02

variables:
  COMMIT_LOG: "1"

build:
  stage: build
  script:
    - ./ci/build
  artifacts:
    paths:
      - ./matomo4nix

run:
  stage: run
  only:
    - schedules
  artifacts:
    paths:
      - ./*.log
      - ./*.json
  script:
    - ./ci/run

test:
  stage: test
  interruptible: true
  script:
    - ./ci/test

push:
  stage: push
  only:
    - schedules
  script:
    - ./ci/push

helsinki_npins:
  stage: npins
  only:
    - schedules
  trigger: helsinki-systems/helsinki
  variables:
    COMMAND: update_pin
    PIN: matomo4nix
