#!/usr/bin/env bash
set -e
set -u
set -o pipefail
set -x

export MATOMO_VERSION=$(nix --option experimental-features nix-command eval --raw --impure --expr '(import <nixpkgs> {}).matomo.version')
./matomo4nix

# vim: set ft=sh sw=4:
